[project]
name = "costofgoodssold"
version = "0.1.0"
description = "Cost of Goods Sold and Inventory Asset Value calculator, with the goal of providing easy for a variety of data sources relevant to business use."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.1.1",
    "setuptools>=84.0.0",
]
